### ISSUE TITLE
Make Extractor and (Tensorflow) Trainer realize the benchmark it's using

### ISSUE THREAD

**Issue by crystina-z** [capreolus-ir/capreolus#108]
Currently, two different benchmarks would share exactly the same extractor and trainer cache path (where `qid2toks` and `docid2passage`, training/dev/test data, and everything are stored).

related to the refactor mentioned in #105

**Comment by andrewyates** [comment]
What do you think about immediately adding benchmark as a dependency to both of these? That should work with no other changes and would reduce the possibility of anyone not aware of this issue from creating a caching bug for themselves

**Comment by crystina-z** [comment]
sure, will put them in `feature/autotokenizer`?

**Comment by andrewyates** [comment]
sounds good
