### ISSUE TITLE
when to set is_large_collection True?

### ISSUE THREAD

**Issue by ali-abz** [capreolus-ir/capreolus#133]
Hi there,
I am trying to create a new collection of Persian Wikipedia and it contains about 1.4 million paragraphs which I am willing to index and use. I did not found any documentation regarding when to set `is_large_collection` to True or what it does.

I would appreciate any comments.

**Comment by andrewyates** [comment]
Hi Ali, currently `is_large_collection` should always be True. When False, it creates a lean Anserini index (no raw text, term positions, etc), but you will run into trouble when retrieving raw text from the index fails.

**Comment by ali-abz** [comment]
I see, thanks.
I wonder why collections like `nf` or `antique` do not set it to True since `is_large_collection` by definition, is set to False.

**Comment by andrewyates** [comment]
Sorry, I got that backwards (and edited above). Collections should not be considered large, so they should all set `is_large_collection=False`.

**Comment by ali-abz** [comment]
Thanks.
