### ISSUE TITLE
error in feature/msmarco_psg

### ISSUE THREAD

**Issue by Tooba-ts1700550** [capreolus-ir/capreolus#150]
I am getting the following error when trying to use msmarcopsg, in benchmarks/msmarco.py at line 60:
IndexError: list index out of range

**Comment by andrewyates** [comment]
This branch hasn't been merged yet, but maybe @crystina-z may be able to help.

**Comment by crystina-z** [comment]
sorry for missing this. If the issue is still valid, @Tooba-ts1700550 could you provide the command and the link to the line that throws the error?
