### ISSUE TITLE
What size of GPU is needed to run CEDR-KNRM

### ISSUE THREAD

**Issue by Eileenluu** [capreolus-ir/capreolus#167]
I was running CEDR-KNRM (the data set is ROBUST04) with a 20G GPU, the program was forced to stop after the documentation was compiled, I want to know what size of GPU is required.

**Comment by andrewyates** [comment]
This depends on the batch size and size of the BERT model you're using. With the default base model, you should be able to run on a 20GB GPU with a small batch size (eg `batch=2`).
