### ISSUE TITLE
What are lr scheduler variables?

### ISSUE THREAD

**Issue by d1shs0ap** [capreolus-ir/capreolus#171]
In the second step of training monoBERT from Scratch (https://github.com/capreolus-ir/capreolus/blob/feature/msmarco_psg/docs/reproduction/MS_MARCO.md), we are instructed to "Train on MS MARCO Passage using the following scripts, while replacing the lr scheduler variables with the one you picked up". Which variables is this referring to? Is it alright if we just copy the script and run it as is?

**Comment by crystina-z** [comment]
they basically refers to the `warmupiters ` and `decayiters`. and sure directly running the script would work.

I just updated the instructions, lmk if there is still anything unclear!
