### ISSUE TITLE
monoBERT resource allocation

### ISSUE THREAD

**Issue by d1shs0ap** [capreolus-ir/capreolus#172]
While trying to train monoBERT, I tried to enter a SLURM job with the following line:
`srun --mem=48G --cpus-per-task=2 --time=8:0:0 --gres=gpu:v100l:4 --pty zsh`

However, I receive the error message:
`srun: error: Unable to allocate resources: Requested time limit is invalid (missing or exceeds some limit)`

Is my SLURM job submission correct? Am I allocating too much (or too little) resources? If not, then how should I resolve this error?

Thanks in advance!

**Comment by crystina-z** [comment]
@d1shs0ap heyy sorry I somehow thought I replied to this. 

`cedar` allows up to 3 hours for `srun` request. For a job with longer running time we can switch to `sbatch`, an example script can be found [here](https://github.com/capreolus-ir/capreolus/blob/feature/msmarco_psg/docs/setup/scripts/sample_slurm_script.sh).

**Comment by d1shs0ap** [comment]
@crystina-z Great, thanks!
