### ISSUE TITLE
How to use capreolus for Robust evaluation？

### ISSUE THREAD

**Issue by yiyaxiaozhi** [capreolus-ir/capreolus#197]
I obtain the model checkpoint on Robust04 fold-2 by the following command:
`python -m capreolus.run rerank.traineval with file=docs/reproduction/config_paradept.txt fold=s2`
but while running the prediction, the progress is killed by accident. Therefore it did not display the test result.
What command should I use to load the checkpoint and run the fold-2 test?

**Comment by andrewyates** [comment]
If training completed, you can replace `rerank.traineval` with `rerank.evaluate` to run only the evaluation. This will only work if all parts of training finished, which includes predictions on the dev set, for example.
