### ISSUE TITLE
Which one of "ndcg_cut_20" and "ndcg_cun_20 [interp]" is the result in reproduces document?

### ISSUE THREAD

**Issue by yiyaxiaozhi** [capreolus-ir/capreolus#198]
I follow the instruction of [https://github.com/capreolus-ir/capreolus/blob/master/docs/reproduction/PARADE.md](url) to reproduce the PARADE result with extra layer on my way. After I train the modified PARADE cross 5 folds and obtain this message:
![image](https://user-images.githubusercontent.com/44088154/143735099-952e68a9-a26b-47ff-b4b0-c18161cf73e9.png)
Here are "**ndcg_cut_20**" and "**ndcg_cun_20 [interp]**", which one should be compared with the reported result of capreolus/docs/reproduction/PARADE.md?  :
![image](https://user-images.githubusercontent.com/44088154/143735135-9040876e-a848-4397-9893-69420ca1752d.png)

**Comment by andrewyates** [comment]
The reproduction document reports ndcg_cut_20 without interpolation ("ndcg_cut_20")
